-- Public demo tasks. These records have no owning auth user and are read-only through RLS.
insert into public.tasks (
  id,
  business_name_snapshot,
  title,
  category,
  description,
  desired_outcome,
  scope_summary,
  deliverables,
  acceptance_criteria,
  skills,
  budget_amount,
  estimated_hours,
  duration_label,
  location,
  status,
  visibility,
  progress
)
values
  (
    '11111111-1111-4111-8111-111111111111',
    'Mylai Filter House',
    'Create a QR menu for our café',
    'Web & no-code',
    'Turn our printed two-page menu into a mobile-friendly QR menu that is easy for our team to update.',
    'Customers can browse the current menu quickly from any phone.',
    'Build a fast, mobile-first digital menu with clear categories, prices and a printable QR code.',
    array['Responsive one-page menu', 'Editable menu content', 'Print-ready QR code'],
    array['Loads on 4G in under 3 seconds', 'All prices match the approved sheet', 'QR scans from an A5 tabletop card'],
    array['Next.js', 'Canva', 'Mobile UI'],
    3500,
    8,
    '4–6 days',
    'Mylapore',
    'open',
    'public',
    12
  ),
  (
    '22222222-2222-4222-8222-222222222222',
    'Vetri Home Services',
    'Fix our Google Business profile',
    'Local marketing',
    'Improve our local search profile, add missing service details and create a simple review link for customers.',
    'Customers can find accurate services and leave a review easily.',
    'Audit and refresh the business profile, organize service information and prepare a lightweight review-request kit.',
    array['Profile audit checklist', 'Updated services and description', 'Customer review link card'],
    array['Profile completeness reaches 100%', 'All six services have accurate descriptions', 'Review link works on Android and iPhone'],
    array['Google Business', 'SEO', 'Copywriting'],
    2500,
    5,
    '3–4 days',
    'Porur',
    'reviewing',
    'public',
    30
  ),
  (
    '33333333-3333-4333-8333-333333333333',
    'Kaveri Books',
    'Build a simple event registration page',
    'Web & no-code',
    'Create a small registration page and confirmation message for our weekend children’s reading event.',
    'Parents can register from a phone and the shop receives a clean attendee list.',
    'Create a mobile registration flow with required fields, confirmation copy and an exportable attendee sheet.',
    array['Mobile registration page', 'Confirmation message', 'Exportable attendee sheet'],
    array['Form works on current Android and iPhone browsers', 'Required fields are validated', 'Owner can export registrations to CSV'],
    array['Forms', 'Mobile UI', 'Google Sheets'],
    4000,
    9,
    '5–7 days',
    'Anna Nagar',
    'open',
    'public',
    8
  )
on conflict (id) do update set
  business_name_snapshot = excluded.business_name_snapshot,
  title = excluded.title,
  category = excluded.category,
  description = excluded.description,
  scope_summary = excluded.scope_summary,
  deliverables = excluded.deliverables,
  acceptance_criteria = excluded.acceptance_criteria,
  skills = excluded.skills,
  budget_amount = excluded.budget_amount,
  estimated_hours = excluded.estimated_hours,
  duration_label = excluded.duration_label,
  location = excluded.location,
  visibility = excluded.visibility,
  updated_at = now();
